# Generated by Django 6.0.4 on 2026-06-27 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, подписанные на категорию', related_name='subscribes_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
